### ISSUE TITLE
Flag to skip the watch task when building assets

### ISSUE THREAD

**Issue by u01jmg3** [uofa/gulp-starter#26]
- `skipWatch`

**Comment by robertmain** [comment]
Why not have separate top level tasks? One for gulp:build and one for gulp:watch. Then have gulp:watch call gulp build - no need for an extra command switch that way :smile:

**Comment by u01jmg3** [comment]
[It's already like that](https://github.com/uofa/gulp-starter/blob/master/gulpfile.js#L700-L702) so to be honest the flag would be meaningless as I can simply call `gulp app:build:local` and my watch task won't be run

**Comment by robertmain** [comment]
:+1: that's true actually....I'd forgotten
