### ISSUE TITLE
Enable 2 flags for the local serve task to customise the URL to be opened or bypass opening a URL entirely

### ISSUE THREAD

**Issue by u01jmg3** [uofa/gulp-starter#27]
- `--pageToOpen page/to/open`

OR

- `skipPageOpen`

**Comment by 321zeno** [comment]
:heart:

**Comment by 321zeno** [comment]
What about adding the option inside `config.json` ?

**Comment by u01jmg3** [comment]
I think it could change to much depending on what route you're currently working on
