### ISSUE TITLE
Modify watch task to include monitoring changes in `bower_components` & `bower.json`

### ISSUE THREAD

**Issue by u01jmg3** [uofa/gulp-starter#30]
- Modify watch task to include monitoring changes in `bower_components` and then re-build scripts
- Modify watch task to include monitoring changes in `bower.json`, install new dependencies and then re-build scripts
  - Thanks @robertmain

**Comment by robertmain** [comment]
Why not have it watch `bower.json` for changes and then re-run the install dependencies task on change? That way you could manage bower deps just by editing the bower file which would be pretty nice!
