### ISSUE TITLE
Combine `global-version` functionality with master and use a config var to toggle between local/global usage

### ISSUE THREAD

**Issue by u01jmg3** [uofa/gulp-starter#37]
- Dependent on [#36 Change config variable name to represent use](https://github.com/uofa/gulp-starter/issues/36)

---

- ~~Break out dependencies defined in [npm-installs.bat](https://github.com/uofa/gulp-starter/blob/global-version/npm-installs.bat) into a _package.json_ ([like master](https://github.com/uofa/gulp-starter/blob/master/package.json))~~
  - Issue with npm installing dependencies to `npm-cache` and not `node_modules` even though `--global` is used
- [x] Update instructions

**Comment by robertmain** [comment]
This would be particularly nice with the functionality mentioned in #39
