### ISSUE TITLE
Add the ability to generate a compressed CSS file

### ISSUE THREAD

**Issue by 321zeno** [uofa/gulp-starter#49]
- The generated CSS filesize can be decreased by stripping all whitespace.
- This can be achieved by running:

```js
// Tasks: local.js and remote.js

var sassSettings = { precision: 10 };
if (!argv.skipMinify) {
    sassSettings['outputStyle'] = 'compressed';
}
...
.pipe(iff('*.scss', sass(sassSettings).on('error', onError)))
```

**Comment by u01jmg3** [comment]
Production only setting?

**Comment by darrencoutts118** [comment]
Have a look at: https://www.npmjs.com/package/gulp-cssnano

**Comment by 321zeno** [comment]
I was thinking of toggling this depending on the `--skip-minify` flag which is already used for the js assets

**Comment by u01jmg3** [comment]
Will put a PR together

@darrencoutts118: thanks for the suggestion but for now I think we will stick with the dependencies we have unless there is cause to change them
